---
- hosts: controllers
  become: yes
  remote_user: heat-admin
  tasks:
    - name: copy  theme
      copy:
        src: openstack-horizon-remo-theme/
        dest: /usr/share/openstack-dashboard/openstack_dashboard/themes/
        owner: root
        group: root
        directory_mode: yes
      tags: copy_files

