- hosts:  packstack
  become: yes
  remote_user: remo
  tasks:
    - name: editing openstack local config
      blockinfile:
       path: /etc/openstack-dashboard/local_settings
       marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK -->"
       insertafter: '#CUSTOM_THEME_PATH'
       content: |
          DEFAULT_THEME = 'Avi'
          AVAILABLE_THEMES = [
          ('default', 'Default', 'themes/default'),
          ('material', 'Material', 'themes/material'),
          ('Avi', 'Avi Networks', 'themes/avi'),
           ]

          LAUNCH_INSTANCE_DEFAULTS = {
           'create_volume': False,
           }
          SITE_BRANDING = 'Avi Networks'
      tags: edit_local_settings
    - name: create_volume changes
      replace:
        path: /etc/openstack-dashboard/local_settings
        regexp: "'create_volume': True,"
        replace: "'create_volume': False,"
      changed_when: True
      tags: create

    - name: copy  theme
      copy:
        src: avi
        dest: /usr/share/openstack-dashboard/openstack_dashboard/themes/
        owner: root
        group: root
        directory_mode: yes
      tags: theme

    - name: restart httpd
      command: systemctl restart httpd
