- hosts: controllers
  become: yes
  remote_user: vagrant
  tasks:
    - name: editing openstack local config
      blockinfile:
       path: /etc/openstack-dashboard/local_settings
       marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK -->"
       insertafter: '#CUSTOM_THEME_PATH'
       content: |
          DEFAULT_THEME = 'Juve'
          AVAILABLE_THEMES = [
          ('default', 'Default', 'themes/default'),
          ('material', 'Material', 'themes/material'),
          ('Juve', 'Juventus', 'themes/juventus'),
           ]
          LAUNCH_INSTANCE_DEFAULTS = {
           'create_volume': False,
           }
          SITE_BRANDING = 'Juventus, Inc. Cloud'
      tags: edit_local_settings
    - name: copy  theme
      copy:
        src: openstack-horizon-remo-theme/
        dest: /usr/share/openstack-dashboard/openstack_dashboard/themes/
        owner: root
        group: root
        directory_mode: yes
      tags: theme

    - name: restart httpd
      command: systemctl restart httpd
